<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Simplix.PortalClient.Application\Simplix.PortalClient.Application.csproj" />
    <ProjectReference Include="..\Simplix.PortalClient.Infrastructure\Simplix.PortalClient.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8d9c2f61-6a96-4c18-a917-5d6276dfa4cc</UserSecretsId>
  </PropertyGroup>

</Project>

